version: '3'
services:
  api-server:
    image: api-server:python3.6.6-stretch-slim
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NGINX_VERSION: 1.15.3-1~stretch
        NJS_VERSION: 1.15.3.0.2.3-1~stretch
    container_name: api-server
    volumes:
      - ../:/app
    ports:
      - "8080:80"
    restart: always
